### ISSUE TITLE
Setting to force rebase

### ISSUE THREAD

**Issue by oskarkrawczyk** [kennethreitz/legit#102]
Hey this is Oskar from JSFiddle.

Love Legit, one thing that annoys me and kills the workflow we have set is the smart-rebase that's not so smart.

Long story short, we **always** use rebase, we even have `pull.rebase = true` in gitconfig, unfortunately Legit, completely ignores this setting.

Any chance we could get a Legit setting that enforces rebasing all the time?

I see, I'm not the only one here who would like this to be there.

**Comment by wkentaro** [comment]
+1

**Comment by wkentaro** [comment]
Currently, `scm:smart_pull()` does Fetch, Rebase/Merge.
So this is equivalent to
```
$ git checkout branch0
$ git fetch origin
$ git rebase origin/branch0 || { git rebase --abort ; git merge origin/branch0 }
```


And in my understanding, you'd like to use `pull.rebase=True` and this is same as:
```
$ git checkout branch0
$ git pull --rebase origin branch0
```
Are there differences between the two workflows results?
@oskarkrawczyk
