### ISSUE TITLE
Seperate legit into liblegit and legit-cli

### ISSUE THREAD

**Issue by MaPePeR** [kennethreitz/legit#104]
In the current state of the program it is not possible to use legit as a library.

For several reasons: 
1. `scm.repo_check()` uses `sys.exit(128)` instead of raising an Exception.
2. For some commands the legit-logic is heavily mixed with cli-logic. See `cli.cmd_sync`.
3. Functions that implement the legit-logic don't take arguments, but work with a global shared variable `repo`

I think separating the cli-handling from legit-commands would be useful.
Leaving the logic of `sync` untouched, but use it like `sync(repo,remote=master)`

This would also clean up the code, so that not each scm-function needs to call `repo_check`.

**Comment by weakish** [comment]
Close it for now. Pull requests are welcome though.
