### ISSUE TITLE
cannot install legit from pip

### ISSUE THREAD

**Issue by cyluss** [kennethreitz/legit#120]
I cannot install legit from pip.

The setup script could not find proper gitpython version. 

Please fix this issue.

    vagrant@precise32:~$ sudo pip install legit
    Downloading/unpacking legit
      Downloading legit-0.1.1.tar.gz
      Running setup.py egg_info for package legit
        
    Downloading/unpacking clint>=0.2.4 (from legit)
      Downloading clint-0.3.1.tar.gz
      Running setup.py egg_info for package clint
        
    Downloading/unpacking gitpython>=0.3.0 (from legit)
      Could not find a version that satisfies the requirement gitpython>=0.3.0 (from legit) (from versions: 0.1.7, 0.2.0-beta1, 0.3.0-beta1, 0.3.0-beta2, 0.3.1-beta2, 0.3.2.RC1)
    Cleaning up...
    No distributions matching the version for gitpython>=0.3.0 (from legit)
    Storing complete log in /home/vagrant/.pip/pip.log
    vagrant@precise32:~$

**Comment by hickford** [comment]
Fixed by https://github.com/kennethreitz/legit/commit/1f571e83b9ec64b183a3482b6c5f89d555d22cbc

Try installing from develop:

    pip install git+https://github.com/kennethreitz/legit.git@develop

Does that install correctly? Otherwise please reopen the issue
