### ISSUE TITLE
Can't find a version of gitpython to install legit

### ISSUE THREAD

**Issue by santagada** [kennethreitz/legit#127]
There is something wrong with the depencies definition (and of course with gitpython release numbers):

```
Downloading/unpacking gitpython>=0.3.0 (from legit)
  Could not find a version that satisfies the requirement gitpython>=0.3.0 (from legit) (from versions: 0.1.7, 0.2.0-beta1, 0.3.0-beta1, 0.3.0-beta2, 0.3.1-beta2, 0.3.2.RC1)
Cleaning up...
No distributions matching the version for gitpython>=0.3.0 (from legit)
```

**Comment by hickford** [comment]
Fixed by https://github.com/kennethreitz/legit/commit/1f571e83b9ec64b183a3482b6c5f89d555d22cbc

Try installing from develop:

    pip install git+https://github.com/kennethreitz/legit.git@develop

Does that install correctly? Otherwise please reopen the issue
