### ISSUE TITLE
Update homebrew formula for legit

### ISSUE THREAD

**Issue by suan** [kennethreitz/legit#128]
The [current homebrew formula](https://github.com/mxcl/homebrew/blob/master/Library/Formula/legit.rb) is still for v0.1.0, which has the bad incorrect stash pop bug as fixed by #85. Any chance somebody could update it?

**Comment by bogem** [comment]
Updated https://github.com/Homebrew/homebrew/commit/b6459f14d4ef56f10d20ed98d8eee9876b92627f

**Comment by hickford** [comment]
Thanks!
