### ISSUE TITLE
When will you release new version of legit to pip package list?

### ISSUE THREAD

**Issue by doggy8088** [kennethreitz/legit#135]
It looks like you changed a lot in the develop branch and the current release version is not that compatible with the latest Python installation especially for clint issue and Args issue, also the 'legit install' failed on Windows issue that I've just submitted by pull request just a moment ago.  I'd like to ask what when will you release new version of legit to pip package list? Thanks.

**Comment by zombat** [comment]
Yes. That would be nice to have the current version on PyPi. 

I just installed the current development Branch with [Pipsi](https://github.com/mitsuhiko/pipsi) like this: 
`pipsi install git+https://github.com/kennethreitz/legit.git@develop#egg=Legit`

**Comment by hickford** [comment]
Yes you can install from master

    pip install git+https://github.com/kennethreitz/legit.git@develop

**Comment by hickford** [comment]
Published v0.2.0 to https://pypi.python.org/pypi/legit/
