### ISSUE TITLE
Not working after Mavericks upgrade?

### ISSUE THREAD

**Issue by JamesMcFall** [kennethreitz/legit#150]
Hey Kenneth,
After my upgrade to Mavericks, legit stopped working for me. I'm hoping I'm not doing something stupid.

```
$ git branches
legit branches: legit: command not found
fatal: While expanding alias 'branches': 'legit branches': No such file or directory
```

After wondering if it'd been uninstalled I tried reinstalling:

```
$ brew install legit
Warning: legit-0.1.0 already installed
$ legit install
-bash: legit: command not found
```

Thanks!

**Comment by StevenACoffman** [comment]
This is not a problem with legit, but when you upgrade to Mavericks, you will need to relink your brew files. You are probably having other problems, so here's a handy fix:
```bash
for l in `brew list`; do brew unlink $l; brew link --overwrite $l; done
```bash
