### ISSUE TITLE
Project stalled/abandoned?

### ISSUE THREAD

**Issue by wamatt** [kennethreitz/legit#154]
Perhaps we can have a discussion about the status:

Open issues are piling up. Critical ones like simply installing legit, go unanswered.
Almost no new commits. And last issue was closed in May. Now new pull requests.

Ping @kennethreitz

**Comment by Konafets** [comment]
What is the status here?

**Comment by hickford** [comment]
I'll do what I can to merge pull requests. I don't have the permissions to publish to PyPI.

**Comment by hickford** [comment]
If you feel trusting you could add me as a maintainer? My username on PyPI is 'hickford' I publish two other packages

https://pypi.python.org/pypi?:action=role_form&package_name=legit

**Comment by kennethreitz** [comment]
@hickford is now able to publish new releases of legit! 

Many thanks for keeping this wonderful project alive!

**Comment by wamatt** [comment]
nice one @kennethreitz. on behalf of everyone, ty for allowing things move forward. :+1:

**Comment by hickford** [comment]
Thanks Kenneth! I've published a Python 3 compatible release, v0.2.0

* https://pypi.python.org/pypi/legit/
* https://github.com/kennethreitz/legit/releases

**Comment by hickford** [comment]
@kennethreitz one more thing, it would be useful if you could flick the switch for kennethreitz/legit at https://travis-ci.org/profile/kennethreitz

**Comment by hickford** [comment]
I also nominate Kentaro @wkentaro for another collaborator. Thanks for all the pull requests

**Comment by wkentaro** [comment]
Thanks. I'm willing to help to proceed with this project.
