### ISSUE TITLE
legit.exe checked in git repository

### ISSUE THREAD

**Issue by weakish** [kennethreitz/legit#161]
legit.exe is checked in `build/legit/`.

What about removing it from the repository and attach it to GitHub Releases?

**Comment by hickford** [comment]
You're right, you can attach downloads to releases now (eg. https://github.com/ssllabs/ssllabs-scan/releases/tag/v1.1.0). That would be neater, good idea.

**Comment by hickford** [comment]
Done! Attached legit.exe to https://github.com/kennethreitz/legit/releases/tag/v0.2.0

I should add a link from the readme.

**Comment by hickford** [comment]
Done https://github.com/kennethreitz/legit/commit/516ca0de324c95d3d5e88774f22a094dc30aa586
