### ISSUE TITLE
PyPI installation in Python 3 gives print statement error

### ISSUE THREAD

**Issue by ericmjl** [kennethreitz/legit#165]
Error as below:

	Collecting legit
	  Downloading legit-0.1.1.tar.gz
	    Complete output from command python setup.py egg_info:
	    Traceback (most recent call last):
	      File "<string>", line 20, in <module>
	      File "/private/var/folders/7b/fw10n6f17tb3zbhxd82pl51r0000gn/T/pip-build-vhsgog9t/legit/setup.py", line 37
	        print 'py2exe is required to continue.'
	                                              ^
	    SyntaxError: Missing parentheses in call to 'print'
	    
	    ----------------------------------------
	Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7b/fw10n6f17tb3zbhxd82pl51r0000gn/T/pip-build-vhsgog9t/legit

**Comment by hickford** [comment]
https://pypi.python.org/pypi/legit/

The version on PyPI is old (2012), try installing from master instead

    pip install git+https://github.com/kennethreitz/legit.git@develop

**Comment by ericmjl** [comment]
Looks like it worked! Would you like any help getting the latest version onto Binstar and PyPI? Or are you working on a few more things?

**Comment by hickford** [comment]
I think only Kenneth can publish to PyPI
