### ISSUE TITLE
Contributing to legit

### ISSUE THREAD

**Issue by TheTeraByte** [kennethreitz/legit#172]
Hi! I wanted to contribute to the project but wasn't sure how to go about it (there wasn't anything in the README). Is there any bug or feature request I can be assigned to?

**Comment by wkentaro** [comment]
maybe you can read the issues at:
https://github.com/kennethreitz/legit/issues

and also TODO.rst:
https://github.com/kennethreitz/legit/blob/develop/TODO.rst

**Comment by wkentaro** [comment]
@TheTeraByte 
Could you please work for this? https://github.com/kennethreitz/legit/issues/184

**Comment by TheTeraByte** [comment]
I'll take a look at it this weekend!
