### ISSUE TITLE
legit emits error: "Not a git repository" on git subtree

### ISSUE THREAD

**Issue by davidthewatson** [kennethreitz/legit#197]
I have a git repository with 3 git subtrees. If I'm in one of the subtree directories and I issue a legit command, legit emits "Not a git repository"; however, git recognizes that the directory is part of the subtree and responds as expected.

```
[monolith] ~/Source/monolith/dog 10-api-returns-role$ git branch
* 10-api-returns-role
  master
[monolith] ~/Source/monolith/dog 10-api-returns-role$ legit branches
Not a git repository.
```

**Comment by weakish** [comment]
I have tested with `develop` branch HEAD against a repository with 2 git subtrees.
And `legit branches` works okay.
Thus I guess this has been fixed in recent versions of legit.
Close for now. Reopen it if this does not work on your machine.
