### ISSUE TITLE
Creating Pull Request from Terminal

### ISSUE THREAD

**Issue by hamt3ch** [kennethreitz/legit#200]
Feature Request: Allow users to create a PR for the command line...
EX: git pull_request master <branchname> -m "Comment in message"

**Comment by kennethreitz** [comment]
I considered this! However, I decided that this is a Git client, not a GitHub client.

**Comment by acrobat** [comment]
If you want that feature you can use [hub](https://hub.github.com/)

**Comment by kennethreitz** [comment]
+10, hub is great

**Comment by lf-** [comment]
This plus hub would be a killer combination.

**Comment by kura** [comment]
@lf- I wrote a little snippet to make hub and legit work together - https://github.com/kennethreitz/legit/issues/219
