### ISSUE TITLE
simple explination of when to use sync vs resync

### ISSUE THREAD

**Issue by bobcolner** [kennethreitz/legit#202]
love the idea of this tool, but the resync command confuses me. Does anyone know when it should be used? Thanks.

**Comment by dmitriyK1** [comment]
If I understand correctly it's used to synchronize current branch with master branch

**Comment by weakish** [comment]
`sync` involves 2 branches: pull from `upstream`, merge/rebase with `local`, then push to `upstream`.

`resync` involves 3 branches: pull from two upstream branches, merge/rebase with `local`, then push to one upstream branches.

For example, the current branch is `foo`. `sync` will sync local `foo` with `remote/foo`,
and `resync` will pull from `remote/master` and `remote/foo`, then sync local `foo` with `remote/foo`.
After `resync`, local `foo` and `remote/foo` will be the same, and both contain changes in `remote/master`, but `remote/master` is intact.

Currently I think `resync` has the following problems:

- The help message is not very clear.
- The name `resync` is confusing.
- `sync` can accept one `branch` argument. Accordingly `resync` should accept tow arguments, one for the upstream branch, one for the sync branch. But currently `resync` only accept one argument (the former).

**Comment by kennethreitz** [comment]
resync should removed.
