### ISSUE TITLE
dictionary changed size during iteration, when trying to run with python3.5

### ISSUE THREAD

**Issue by elopio** [kennethreitz/legit#212]
Using python3.5, after removing the spurious print in #211, I get:

$ legit
legit. A Kenneth Reitz Project

Usage: legit <command>

Commands:

Traceback (most recent call last):
  File "/snap/legit/x2/bin/legit", line 11, in <module>
    sys.exit(main())
  File "/snap/legit/x2/lib/python3.5/site-packages/legit/cli.py", line 61, in main
    display_help()
  File "/snap/legit/x2/lib/python3.5/site-packages/legit/cli.py", line 575, in display_help
    display_info()
  File "/snap/legit/x2/lib/python3.5/site-packages/legit/cli.py", line 557, in display_info
    for command in sort_with_similarity(commands, key=lambda x:x.name):
  File "/snap/legit/x2/lib/python3.5/site-packages/legit/cli.py", line 532, in sort_with_similarity
    for k in left_iterable.keys():
RuntimeError: dictionary changed size during iteration

**Comment by yangnw** [comment]
I second that. `legit` from pip in python 3.6.0 produces that same error, while under that from pip in python 2.7 works fine.

**Comment by ofek** [comment]
+1 Any idea why @kennethreitz?

**Comment by kapinga** [comment]
dict.keys() returns a generator in Python 3, but in Python 2, dict.keys() returns a list. This means that iterating over dict.keys() falls over if you modify the dict on the fly.

There's an easy fix: change line 401 in cli.py from:
`    for k in left_iterable.keys():`
to
`    for k in list(left_iterable.keys()):`

Someone should probably make a PR, I don't have the repo forked and it seems like overkill for such a simple change.

**Comment by vatsalparekh** [comment]
I just encountered this error

**Comment by weakish** [comment]
@vatsalparekh  Which version are you using?  #217 did not fix this?

**Comment by weakish** [comment]
This has been fixed in #217.

Not released for pip yet.
