### ISSUE TITLE
remove most commands

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/legit#215]
leave:

- sync
- undo
- branches
- switch
- settings
- publish
- unpublish
- install

remove: 

- graft
- harvest
- help
- sprout

**Comment by gaojiuli** [comment]
Since there is a 'undo' command, there should be a redo command.

**Comment by reneruiz** [comment]
What's the reasoning for removing sprout, harvest, and graft?

**Comment by kennethreitz** [comment]
@reneruiz I use legit every day, and I never use those features.
