### ISSUE TITLE
Please add windows build for latest release

### ISSUE THREAD

**Issue by fsateler** [kennethreitz/legit#216]
Release 0.2.1 is missing the windows binary. Thanks!

**Comment by kennethreitz** [comment]
If anyone wants to help with this, it'd be a great contribution!

**Comment by weakish** [comment]
What is the tool used to package for Windows in previous releases?
I have not found any doc.

**Comment by weakish** [comment]
Windows binary added.

The binary is packaged with Python 2.7.13 and Pyinstaller with `export PYTHONHASHSEED=1`
on [32-bit Windows 7 SP1][test-vm].

[test-vm]: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
