### ISSUE TITLE
Merge with git-extras

### ISSUE THREAD

**Issue by bersace** [kennethreitz/legit#224]
Hi,

Why not merge with https://github.com/tj/git-extras/ ? git-extras is more popular and has been there before.

Regards,
Étienne

**Comment by kennethreitz** [comment]
no

**Comment by bersace** [comment]
After reading https://www.kennethreitz.org/values/ , I though the anwser of *why* would be more positive.

kthxbye

**Comment by kennethreitz** [comment]
just too lazy to type :)

Basically, git-extras is awesome, i know the guy — but there's a lot of overlap and i like legit being it's own thing.

**Comment by weakish** [comment]
@bersace  I am overwhelmed by the command list of git, and the command list of git extra.

**Comment by kennethreitz** [comment]
indeed
