### ISSUE TITLE
Loop over N git repos

### ISSUE THREAD

**Issue by guettli** [kennethreitz/legit#227]
I often work with several git repos at once:

- core product (for example a commercial issue tracker)
- optional plugin for above core product
- customer configuration

Use case: I want to create a branch on all three git repos.

Can `legit` loop over N git repos?

**Comment by weakish** [comment]
No.

But you can use `legit` with [clustergit] or [gr].

For example,
Assuming all git repos are sub directories of the current working directory,
and you have installed the legit sync aliases.

```
# If you are using clustergit:
clusetergit --exec 'git sync'

# If you are using gr:
gr tag work # first time only
gr @work sync
```

[clustergit]: https://github.com/mnagel/clustergit
[gr]: https://github.com/mixu/gr

**Comment by guettli** [comment]
Thank you for the explanation.
