### ISSUE TITLE
Release legit 0.5.0 on PyPi

### ISSUE THREAD

**Issue by kdeldycke** [kennethreitz/legit#229]
legit 0.5.0 has just been released but the available version on PyPi is 0.4.1: https://pypi.python.org/pypi/legit

Can we publish legit 0.5.0 on PyPi? :)

**Comment by weakish** [comment]
Technically 0.5.0 has not been released yet.
I just updated the version number in code and  HISTORY.rst last week.

**Comment by grahamu** [comment]
legit v1.0.0 is published to PyPi https://pypi.python.org/pypi/legit/
