### ISSUE TITLE
Looser version pinnings?

### ISSUE THREAD

**Issue by pmlandwehr** [kennethreitz/legit#237]
I'm interested in updating the [conda-forge build](https://github.com/conda-forge/legit-feedstock/pull/2) of `legit`. The version pinnings for building and running are quite strict, and I'm wondering if they can be loosened. (e.g. `six` is now at `1.11.0`) Is that feasible? I'd be happy to make a pull request.

**Comment by grahamu** [comment]
I have no problem updating specific requirement versions, but given this pipenv [setup.py guidance](https://docs.pipenv.org/advanced/#pipfile-vs-setup-py) I'm inclined to let @kennethreitz weigh in on this request.

**Comment by grahamu** [comment]
@pmlandwehr I've published a new release, v1.0.1 to PyPi, with updated requirements. Thanks for the tip!

Please close this issue if the new release solves your problem, otherwise let's discuss (or perhaps PR discuss) how to resolve this. Thanks

**Comment by pmlandwehr** [comment]
I'm going to close this for now - I think this will be ok.
