### ISSUE TITLE
http://www.git-legit.org/ has typo

### ISSUE THREAD

**Issue by josephcslater** [kennethreitz/legit#239]
Unfortunately I didn't find where to make this simple fix. [http://www.git-legit.org/](http://www.git-legit.org/) lists ``legit install`` as a command to install the aliases for ``git``, but is is actually ``legit --install``, of course.

**Comment by grahamu** [comment]
<img width="294" alt="screen shot 2018-03-25 at 5 30 54 pm" src="https://user-images.githubusercontent.com/130456/37881249-53ab8884-3052-11e8-9885-c509c7d9273e.png">
@kennethreitz any chance you can

**Comment by hatsuo** [comment]
kennethreitz/git-legit.org#3

**Comment by hugovk** [comment]
That PR was closed before merge, here's a new one: https://github.com/kennethreitz/git-legit.org/pull/4
