### ISSUE TITLE
Release a current Windows build

### ISSUE THREAD

**Issue by deanhouseholder** [kennethreitz/legit#246]
Please release a current windows build.

**Comment by weakish** [comment]
I made a binary package for v0.2.1 via Python 2.7.13 and Pyinstaller with `export PYTHONHASHSEED=1`.

If anyone who has access to a Windows machine wants to help with this,
may try this configuration.

Perhaps I will made one within a Windows VM,
just need to find some time to configure and install VirtualBox and Windows.

**Comment by weakish** [comment]
@deanhouseholder Windows build attached. See https://github.com/kennethreitz/legit/releases/tag/v1.0.1

I do not use Windows and just tested `legit branches` on a Windows 7 32 bit VM.
Thus this should be considered as an experimental build.

Close this issue for now. If you have encountered any problem, please open a new issue.
