### ISSUE TITLE
i must be missing something about remotes

### ISSUE THREAD

**Issue by pjv** [kennethreitz/legit#52]
i love the idea of making git more human and codifying a set of good practice conventions into a tool like this (and like the mac GUI), but i think i must be missing something basic about the implied workflow, or i am trying to apply it to a use-case that is outside of the domain it is trying to address (or i'm a dope).

the way that i usually set up to contribute to someone else's open source project is to:
1. clone their repo as origin on my local machine
2. fork their repo on github
3. add my fork as an additional remote to my local repo

then i create feature branches on my local machine and push them to my github fork and submit pull requests to the owner **while also being able to fetch/pull from the owner's repo to keep up with their changes.**

if i understand it right, legit is only intended and optimized for working with a single remote (i.e. my fork on github). so in the scenario above of contributing to someone else's project, how do i keep up with their changes? 

i know that i can add an additional remote and just do what i always do outside of legit, but is this something that legit is not intended to address, or am i missing something?

any explanation or pointer to where this is already discussed would be very welcome.

**Comment by weakish** [comment]
This issue should have been fixed in recent versions of legit.
