### ISSUE TITLE
installation fails on cygwin

### ISSUE THREAD

**Issue by lkt** [kennethreitz/legit#56]
~ $ pip install legit
Downloading/unpacking legit
  Downloading legit-0.1.1.tar.gz
  Running setup.py egg_info for package legit
Downloading/unpacking clint>=0.2.4 (from legit)
  Downloading clint-0.3.1.tar.gz
  Running setup.py egg_info for package clint
Downloading/unpacking gitpython>=0.3.0 (from legit)
  Downloading GitPython-0.3.2.RC1.tar.gz (313Kb): 313Kb downloaded
  Running setup.py egg_info for package gitpython
    warning: no files found matching 'README'
Downloading/unpacking gitdb>=0.5.1 (from gitpython>=0.3.0->legit)
  Downloading gitdb-0.5.4.tar.gz (50Kb): 50Kb downloaded
  Running setup.py egg_info for package gitdb
Downloading/unpacking async>=0.6.1 (from gitdb>=0.5.1->gitpython>=0.3.0->legit)
  Downloading async-0.6.1.tar.gz
  Running setup.py egg_info for package async
Downloading/unpacking smmap>=0.8.0 (from gitdb>=0.5.1->gitpython>=0.3.0->legit)
  Downloading smmap-0.8.2.tar.gz
  Running setup.py egg_info for package smmap
Installing collected packages: legit, clint, gitpython, gitdb, async, smmap
  Running setup.py install for legit
    Installing legit script to /usr/bin
  Running setup.py install for clint
    warning: install_data: setup script did not provide a directory for 'README.rst' -- installing right in '/usr'
    warning: install_data: setup script did not provide a directory for 'HISTORY.rst' -- installing right in '/usr'
    Complete output from command /usr/bin/python2.6 -c "import setuptools;**file**='/home/Admin/build/clint/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-k2VYT5-record/install-record.txt:
    running install

running build

running build_py

creating build

creating build/lib

creating build/lib/clint

copying clint/arguments.py -> build/lib/clint

copying clint/eng.py -> build/lib/clint

copying clint/pipes.py -> build/lib/clint

copying clint/resources.py -> build/lib/clint

copying clint/utils.py -> build/lib/clint

copying clint/**init**.py -> build/lib/clint

creating build/lib/clint/textui

copying clint/textui/colored.py -> build/lib/clint/textui

copying clint/textui/cols.py -> build/lib/clint/textui

copying clint/textui/core.py -> build/lib/clint/textui

copying clint/textui/formatters.py -> build/lib/clint/textui

copying clint/textui/progress.py -> build/lib/clint/textui

copying clint/textui/**init**.py -> build/lib/clint/textui

creating build/lib/clint/packages

copying clint/packages/appdirs.py -> build/lib/clint/packages

copying clint/packages/ordereddict.py -> build/lib/clint/packages

copying clint/packages/**init**.py -> build/lib/clint/packages

creating build/lib/clint/packages/colorama

copying clint/packages/colorama/ansi.py -> build/lib/clint/packages/colorama

copying clint/packages/colorama/ansitowin32.py -> build/lib/clint/packages/colorama

copying clint/packages/colorama/initialise.py -> build/lib/clint/packages/colorama

copying clint/packages/colorama/win32.py -> build/lib/clint/packages/colorama

copying clint/packages/colorama/winterm.py -> build/lib/clint/packages/colorama

copying clint/packages/colorama/**init**.py -> build/lib/clint/packages/colorama

running install_lib

creating /usr/lib/python2.6/site-packages/clint

copying build/lib/clint/arguments.py -> /usr/lib/python2.6/site-packages/clint

copying build/lib/clint/eng.py -> /usr/lib/python2.6/site-packages/clint

creating /usr/lib/python2.6/site-packages/clint/packages

copying build/lib/clint/packages/appdirs.py -> /usr/lib/python2.6/site-packages/clint/packages

creating /usr/lib/python2.6/site-packages/clint/packages/colorama

copying build/lib/clint/packages/colorama/ansi.py -> /usr/lib/python2.6/site-packages/clint/packages/colorama

copying build/lib/clint/packages/colorama/ansitowin32.py -> /usr/lib/python2.6/site-packages/clint/packages/colorama

copying build/lib/clint/packages/colorama/initialise.py -> /usr/lib/python2.6/site-packages/clint/packages/colorama

copying build/lib/clint/packages/colorama/win32.py -> /usr/lib/python2.6/site-packages/clint/packages/colorama

copying build/lib/clint/packages/colorama/winterm.py -> /usr/lib/python2.6/site-packages/clint/packages/colorama

copying build/lib/clint/packages/colorama/**init**.py -> /usr/lib/python2.6/site-packages/clint/packages/colorama

copying build/lib/clint/packages/ordereddict.py -> /usr/lib/python2.6/site-packages/clint/packages

copying build/lib/clint/packages/**init**.py -> /usr/lib/python2.6/site-packages/clint/packages

copying build/lib/clint/pipes.py -> /usr/lib/python2.6/site-packages/clint

copying build/lib/clint/resources.py -> /usr/lib/python2.6/site-packages/clint

creating /usr/lib/python2.6/site-packages/clint/textui

copying build/lib/clint/textui/colored.py -> /usr/lib/python2.6/site-packages/clint/textui

copying build/lib/clint/textui/cols.py -> /usr/lib/python2.6/site-packages/clint/textui

copying build/lib/clint/textui/core.py -> /usr/lib/python2.6/site-packages/clint/textui

copying build/lib/clint/textui/formatters.py -> /usr/lib/python2.6/site-packages/clint/textui

copying build/lib/clint/textui/progress.py -> /usr/lib/python2.6/site-packages/clint/textui

copying build/lib/clint/textui/**init**.py -> /usr/lib/python2.6/site-packages/clint/textui

copying build/lib/clint/utils.py -> /usr/lib/python2.6/site-packages/clint

copying build/lib/clint/**init**.py -> /usr/lib/python2.6/site-packages/clint

byte-compiling /usr/lib/python2.6/site-packages/clint/arguments.py to arguments.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/eng.py to eng.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/packages/appdirs.py to appdirs.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/packages/colorama/ansi.py to ansi.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/packages/colorama/ansitowin32.py to ansitowin32.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/packages/colorama/initialise.py to initialise.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/packages/colorama/win32.py to win32.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/packages/colorama/winterm.py to winterm.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/packages/colorama/**init**.py to **init**.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/packages/ordereddict.py to ordereddict.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/packages/**init**.py to **init**.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/pipes.py to pipes.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/resources.py to resources.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/textui/colored.py to colored.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/textui/cols.py to cols.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/textui/core.py to core.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/textui/formatters.py to formatters.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/textui/progress.py to progress.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/textui/**init**.py to **init**.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/utils.py to utils.pyc

byte-compiling /usr/lib/python2.6/site-packages/clint/**init**.py to **init**.pyc

running install_data

warning: install_data: setup script did not provide a directory for 'README.rst' -- installing right in '/usr'

copying README.rst -> /usr

warning: install_data: setup script did not provide a directory for 'HISTORY.rst' -- installing right in '/usr'

copying HISTORY.rst -> /usr

running install_egg_info

running egg_info

creating clint.egg-info

writing clint.egg-info/PKG-INFO

writing top-level names to clint.egg-info/top_level.txt

writing dependency_links to clint.egg-info/dependency_links.txt

writing manifest file 'clint.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found

reading manifest file 'clint.egg-info/SOURCES.txt'

writing manifest file 'clint.egg-info/SOURCES.txt'

Copying clint.egg-info to /usr/lib/python2.6/site-packages/clint-0.3.1-py2.6.egg-info

running install_scripts

writing list of installed files to '/tmp/pip-k2VYT5-record/install-record.txt'

---

Command /usr/bin/python2.6 -c "import setuptools;**file**='/home/Admin/build/clint/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-k2VYT5-record/install-record.txt failed with error code -6 in /home/Admin/build/clint
Storing complete log in /home/Admin/.pip/pip.log

**Comment by weakish** [comment]
If anyone still has this problem, try the legit.exe file which has Python packaged in on the releases page.
