### ISSUE TITLE
Branches deleted remotely still show as published in legit

### ISSUE THREAD

**Issue by justin** [kennethreitz/legit#58]
I had a few branches that were deleted from Github by someone else remotely. When I run 'git branches' they still show up as (published) by legit.  

Trying to call git unpublished gives this error.

```

Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.cli", line 45, in main
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.cli", line 289, in cmd_unpublish
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.cli", line 80, in status_log
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.scm", line 196, in unpublish_branch
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/git.cmd", line 377, in execute
git.exc.GitCommandError: 'git push origin :Story27438231-iphone-order-summary-currency-relayout' returned exit status 1: error: unable to push to unqualified destination: Story27438231-iphone-order-summary-currency-relayout
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'git@github.com:hoteltonight/ht-ios.git'
```

Calling `git branch -d [BranchName]` deletes the local branch, but it will still show as an existing published branch to Legit.

**Comment by wkentaro** [comment]
* `git fetch --prune` is for updating remote information. (using that information legit finds whether the local branch is published or not)
* `git branch -d [BranchName]` should be run after `fetch --prune` because legit does not do that.

After these, there should be no unexpected branches in the list of `legit branches`.

**Comment by wkentaro** [comment]
this alias can be used to remove all merged branches.
```
alias gbda='git branch --merged | command grep -vE "^(\*|\s*master\s*$)" | command xargs -n 1 git branch -d'
```

**Comment by weakish** [comment]
> Trying to call git unpublished gives this error.

The `develop` branch of legit reports

    It seems that the remote branch has been already deleted.
