### ISSUE TITLE
Make branch arg optional for publish/unpublish, just like sync

### ISSUE THREAD

**Issue by aseemk** [kennethreitz/legit#72]
If I'm on a feature (topic) branch, it'd be nice to be able to say just "git pub" or "git unpub" (aliases for publish/unpublish) instead of having to specify the branch's name. Hope that sounds reasonable. =) Great work!

**Comment by wkentaro** [comment]
+1

**Comment by wkentaro** [comment]
Maybe in `develop` branch, it is implemented.
https://github.com/kennethreitz/legit/blob/develop/legit/cli.py#L314

**Comment by wkentaro** [comment]
Now I'm thinking that unpublish without specified branch can be dangerous.
What do u think about this?

**Comment by kennethreitz** [comment]
@wkentaro agreed :)
