### ISSUE TITLE
Black color on black background

### ISSUE THREAD

**Issue by semaperepelitsa** [kennethreitz/legit#79]
I'm using a standard black terminal with white text ("Pro" theme on Mac). And I've noticed that some of the messages are black (because of the slightly transparent background). Before that I thought this was just a blank space. Is this intended to be like that?

```
% git sync
Pulling commits from the server. - white
Already up-to-date. - black
Pushing commits to the server. -white
```

**Comment by jorgebg** [comment]
+1

**Comment by wkentaro** [comment]
+1
