### ISSUE TITLE
weird errors trying to install legit on windows (using git bash shell)

### ISSUE THREAD

**Issue by axfelix** [kennethreitz/legit#83]
Having some issues installing on Windows -- it seemed to work properly from pip, but legit install results in:

$ legit install
The following git aliases have been installed:

error: wrong number of arguments
usage: git config [options]

Config file location
--global use global config file
--system use system config file
...
←[33m←[33mgit←[39m ←[33mgraft←[39m ←[39m '!legit graft "$@"'

any help? thanks!

**Comment by weakish** [comment]
Close it for now since it cannot be reproduced with recent versions of legit.
(Maybe because recent versions of git on windows does not installs to `git.cmd`?)
