### ISSUE TITLE
Support partial branch name in switch command

### ISSUE THREAD

**Issue by sergionalin** [kennethreitz/legit#89]
This is a "nice to have" feature that could save some typing time like:

    legit switch ma

or

    legit switch ter

to switch to ma[ster]

Behavior could be something like:

if given branch exists: switch to it (current behavior).
if it does not: look for given name fragment (case insensitive) in the branches list. If only one branch matches, switch to it. If more than one branch matches: stop and output error with list of matching branches.

**Comment by wkentaro** [comment]
This can be closed.
```
% legit switch ma
Switching to master.
Switched to a new branch 'master'
Branch master set up to track remote branch master from origin.
```
