### ISSUE TITLE
git sync hangs with credentials.helper 

### ISSUE THREAD

**Issue by rvanlaar** [kennethreitz/legit#95]
I use an https url for a public github repo.
After setting: 
git config --global credential.helper 'cache --timeout=3600'

git sync doesn't work hangs with the push
$ git sync
Pulling commits from the server.
Already up-to-date.
Pushing commits to the server.
And it HANGS.

A git push doesn't hang.

**Comment by weakish** [comment]
Close it for now. If the problem still exists, feel free to comment.
